public with sharing class Active_Pricing {
/*
    public Active_Pricing__c activePricing {get; set;}
    public Pricing_Condition__c pricingCondition {get; set;}
    public String accountNumber {get; set;}
    public String materialNumber {get; set;}
    public String commentsExist {get; set;}

    public Active_Pricing(Active_Pricing__c ap,
                          Map<String, String> incoTermsMap,
                          Map<String, SAP_Plant__c> plantsMap) {
        activePricing = ap;
        pricingCondition = ap.Pricing_Condition__r;
        accountNumber = String_Functions.removeLeadingZeros(ap.Account__r.AccountNumber);
        materialNumber = String_Functions.removeLeadingZeros(ap.Material2__r.Material_Number__c);
        commentsExist = ''; 
        if (pricingCondition.Comments__c != null && 
            pricingCondition.Comments__c.trim().length() > 0) {
            commentsExist = 'Yes';
        }
    }
*/
}