public class dummyclass{

    public static boolean variable1 =false;
    public static boolean variable2 =false;
    public static boolean variable3 =false;
    public static boolean variable4 =false;
    public static boolean variable5 =false;
    public static boolean variable6 =false;
    public static boolean variable7 =false;
    public static boolean variable8 =false;
    public static boolean variable9 =false;
    public static boolean variable10 =false;
    
    public static void dummymethod(){
        variable1 =True;
        variable2 =True;
        variable3 =True;
        variable4 =True;
        variable5 =True;
        variable6 =True;
        variable7 =True;
        variable8 =True;
        variable9 =True;
        variable10 =True;
    }

}