public inherited sharing class SecureFormsConstants {
    public static final String AURA_OPERATION_RESPONSE_SUCCESS = 'success';
    public static final String AURA_OPERATION_RESPONSE_WARNING = 'warning';
    public static final String AURA_OPERATION_RESPONSE_ERROR = 'error';
    public static final String EMAIL_TEMPLATE_CIP_REMINDER_DEV_NAME = 'CustomerInformationPackedReminder';
    public static final String CUSTOMER_INFORMATION_PACKET_RECORD_TYPE = 'CustomerInformationPacket';
    public static final String CRON_EXPRESSION_FOR_TEST = '0 0 0 15 3 ? 2024';
}